import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Plenković apartments</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plenkovic-apartments.ico" />
      </Head>

      <main></main>

      <footer></footer>
    </div>
  );
};

export default Home;
