import Head from "next/head";

export default function AppHead() {
  return (
    <Head>
      <title>Plenković apartments</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/plenkovic-apartments.ico" />
    </Head>
  );
}
