import Head from "next/head";

export default function AppHead() {
  return (
    <Head>
      <title>Plenković apartments</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/plenkovic-apartments.ico" />
      <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
    </Head>
  );
}
